### Q1. What are the benefits of the built-in array package, if any?

- Arrays are similar to lists. The main difference is that arrays can store only one type of elements; whereas, lists can store different types of elements. When dealing with a huge number of elements, arrays use less memory than lists and they offer faster execution than lists.<br>
- The size of the array is not fixed in Python. Hence, we need not specify how many elements we are going to store into an array in the beginning.<br>
- Arrays can grow or shrink in memory dynamically (during runtime).<br>
- Arrays are useful to handle a collection of elements like a group of numbers or characters.<br>
- Methods that are useful to process the elements of any array are available in 'array' module.<br>

### Q2. What are some of the array package&#39;s limitations?

- An array has a fixed size which means you cannot add/delete elements after creation. You also cannot resize them dynamically.
- Unlike lists in Python, cannot store values of different data types in a single array. 
- Another disadvantage of arrays is that they don't support random access. If you want to get some particular record from an array, you must know its exact index.
- Deleting an item from an array involves copying every preceding element to fill up the gap left behind by the deleted element. Deleting items from an array is very expensive because of this reason.

### Q3. Describe the main differences between the array and numpy packages.

- An array is a single dimensional entity which hold the numerical data, while numpy can have more than 1 dimension.
- If all you're doing is creating arrays of simple data types and doing I/O, the array module will do just fine.on the other hand, if you want to do any kind of numerical calculations, the array module doesn't provide any help with that. NumPy (and SciPy) give you a wide variety of operations between arrays and special functions that are useful not only for scientific work but for things like advanced image manipulation or in general anything where you need to perform efficient calculations with large amounts of data.

### Q4. Explain the distinctions between the empty, ones, and zeros functions.

__empty():__ This function is used to create an array without initializing the entries of given shape and type.

In [1]:
import numpy as np  
x = np.empty([3, 2])  
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


__Zeros():__ The numpy.zeros() function is one of the most significant functions which is used in machine learning programs widely. This function is used to generate an array containing zeros.

In [2]:
import numpy as np  
a=np.zeros(6)  
print(a)

[0. 0. 0. 0. 0. 0.]


__ones():__ The numpy.ones() function returns a new array of given shape and type, with ones.

In [3]:
import numpy as np
b = np.ones(2)
print(b)

[1. 1.]


### Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

numpy.fromfunction() function construct an array by executing a function over each coordinate and the resulting array, therefore, has a value fn(x, y, z) at coordinate (x, y, z).<br>
The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis.

In [4]:
import numpy as np
np.fromfunction(lambda i, j: i == j, (2, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False]])

### Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

If any scaler value such as integer is added to the numpy array then all the elements inside the array will add that value in it.

### Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

It will carry out provided operation on all elements of array.

### Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

We can assign fixed-length strings to numpy arrays by changing array type to 'U256'. The maximum length of the string that we can assign in this case after changing the dtype is 256.  If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length accept upto those values which are under the limit.

In [17]:
import numpy as np
country = np.array(['USA', 'Japan', 'UK', '', 'India', 'China'])
print(country)

['USA' 'Japan' 'UK' '' 'India' 'China']


In [18]:
country = country.astype('U256')

In [19]:
country[country == ''] = 'asifjasdjfijadsifjasfcjsajjsaasjjcsjajclsjlcjklcjlksalcjaslkfklajfkljklaskklsklajklajskljklasjksklaklasjskdaksklasklsadklasdkaskldklklaskldlksakldakld'

In [22]:
print(len(country[3]))

150


### Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

It will simply add or multiply element to element at same position.

### Q10. What is the best way to use a Boolean array to mask another array?

The best way to use a Boolean array to mask another array is by Using __masked_where__ of numpy package.

### Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

We can use __statistics.stdev()__ and __numpy.std()__ functions to collect standard deviation.

### 12. What is the dimensionality of a Boolean mask-generated array?

It will have same dimensionality as input array.